# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u9898\u76ee')),
                ('type', models.CharField(blank=True, choices=[('s', '\u5355\u9009'), ('m', '\u591a\u9009')], default='s', max_length=2, verbose_name='\u9009\u62e9\u9898\u7c7b\u578b')),
                ('answer_1', models.CharField(blank=True, default='', max_length=100, verbose_name='\u9009\u9879A')),
                ('answer_2', models.CharField(blank=True, default='', max_length=100, verbose_name='\u9009\u9879B')),
                ('answer_3', models.CharField(blank=True, default='', max_length=100, verbose_name='\u9009\u9879C')),
                ('answer_4', models.CharField(blank=True, default='', max_length=100, verbose_name='\u9009\u9879D')),
                ('result', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u9009\u5219\u9898',
                'verbose_name_plural': '\u9898\u76ee\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='FillBlankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='\u9898\u76ee')),
                ('correct', models.CharField(blank=True, default='', max_length=100, verbose_name='\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u586b\u7a7a\u9898',
                'verbose_name_plural': '\u9898\u76ee\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='PaperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u9898\u5e93\u540d\u79f0')),
                ('created_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u9898\u5e93',
                'verbose_name_plural': '\u9898\u5e93\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='fillblankmodel',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.PaperModel'),
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.PaperModel'),
        ),
    ]
